### wttr
GET https://wttr.in/{Hyderabad}?format=4



### jina
GET https://r.jina.ai/https://www.thedailyjagran.com/india/tdp-mla-nandamuri-balakrishna-calls-jagan-mohan-reddy-psycho-what-prompted-actorturnpolician-to-make-controversial-remark-10269673
